import { useState } from "react";
import { Pill, Sparkles, Loader2 } from "lucide-react";
import { motion } from "framer-motion";
import api from "../services/api";

export default function PrescriptionAnalyzer() {
  const [medicine, setMedicine] = useState("");
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState("");

  const handleAnalyze = async () => {
    if (!medicine.trim()) {
      alert("Enter a medicine name.");
      return;
    }

    try {
      setLoading(true);

      const res = await api.post("/prescriptions", {
        medicine,
      });

      setResponse(res.data.response);

    } catch (err) {
      console.error(err);
      alert("Failed to analyze medicine.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen text-white fade-up">

      {/* Header */}

      <motion.div
        initial={{ opacity: 0, y: -25 }}
        animate={{ opacity: 1, y: 0 }}
        className="glass-card p-8 mb-8"
      >

        <div className="flex items-center gap-5">

          <div className="w-20 h-20 rounded-3xl bg-gradient-to-br from-red-700 via-red-600 to-red-500 flex items-center justify-center heartbeat">

            <Pill size={42} />

          </div>

          <div>

            <h1 className="text-5xl font-extrabold">
              Prescription Analyzer
            </h1>

            <p className="text-gray-400 mt-3 text-lg">
              Understand medicines, dosage, side effects and precautions with AI.
            </p>

          </div>

        </div>

      </motion.div>

      {/* Input Card */}

      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: .2 }}
        className="glass-card p-10"
      >

        <label className="block mb-3 text-lg font-semibold">
          Medicine Name
        </label>

        <input
          value={medicine}
          onChange={(e) => setMedicine(e.target.value)}
          placeholder="Example: Paracetamol 650mg"
          className="w-full p-5 rounded-2xl bg-[#150707] border border-red-900/30"
        />

        <button
          onClick={handleAnalyze}
          disabled={loading}
          className="red-btn mt-8 flex items-center gap-3"
        >

          {loading ? (
            <>
              <Loader2 size={22} className="animate-spin" />
              Analyzing...
            </>
          ) : (
            <>
              <Sparkles size={22} />
              Explain Medicine
            </>
          )}

        </button>

      </motion.div>

      {/* Loading */}

      {loading && (

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="glass-card mt-8 p-8 text-center"
        >

          <Loader2
            size={55}
            className="mx-auto animate-spin text-red-500"
          />

          <h2 className="text-3xl font-bold mt-6">
            AI is analyzing...
          </h2>

          <p className="text-gray-400 mt-3">
            Reading medicine information...
          </p>

          <p className="text-gray-400">
            Checking dosage...
          </p>

          <p className="text-gray-400">
            Generating explanation...
          </p>

        </motion.div>

      )}

      {/* AI Response */}

      {response && (

        <motion.div
          initial={{ opacity: 0, y: 25 }}
          animate={{ opacity: 1, y: 0 }}
          className="glass-card mt-10 p-8"
        >

          <div className="flex items-center gap-3 mb-6">

            <div className="w-12 h-12 rounded-full bg-gradient-to-br from-red-700 to-red-500 flex items-center justify-center">

              💊

            </div>

            <div>

              <h2 className="text-3xl font-bold">
                AI Medicine Explanation
              </h2>

              <p className="text-gray-400">
                Generated by Rapha AI
              </p>

            </div>

          </div>

          <div className="bg-[#160808] border border-red-900/30 rounded-2xl p-6 whitespace-pre-wrap leading-8 text-gray-200">

            {response}

          </div>

        </motion.div>

      )}

    </div>
  );
}