import { useState } from "react";
import { Activity, Sparkles, Loader2 } from "lucide-react";
import { motion } from "framer-motion";
import api from "../services/api";

export default function SymptomChecker() {
  const [symptoms, setSymptoms] = useState("");
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState("");

  const handleCheck = async () => {
    if (!symptoms.trim()) {
      alert("Please enter your symptoms.");
      return;
    }

    try {
      setLoading(true);

      const res = await api.post("/symptoms", {
        symptoms,
      });

      setResponse(res.data.response);

    } catch (err) {
      console.error(err);
      alert("Failed to analyze symptoms.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen text-white fade-up">

      {/* Header */}

      <motion.div
        initial={{ opacity: 0, y: -25 }}
        animate={{ opacity: 1, y: 0 }}
        className="glass-card p-8 mb-8"
      >

        <div className="flex items-center gap-5">

          <div className="w-20 h-20 rounded-3xl bg-gradient-to-br from-red-700 via-red-600 to-red-500 flex items-center justify-center heartbeat">

            <Activity size={42} />

          </div>

          <div>

            <h1 className="text-5xl font-extrabold">
              AI Symptom Checker
            </h1>

            <p className="text-gray-400 mt-3 text-lg">
              Describe your symptoms and let Rapha AI provide possible health insights.
            </p>

          </div>

        </div>

      </motion.div>

      {/* Input */}

      <motion.div
        initial={{ opacity: 0, y: 25 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: .2 }}
        className="glass-card p-10"
      >

        <label className="block text-lg font-semibold mb-4">
          Describe Your Symptoms
        </label>

        <textarea
          rows={7}
          value={symptoms}
          onChange={(e) => setSymptoms(e.target.value)}
          placeholder="Example: Fever, cough, sore throat, body pain, headache..."
          className="w-full bg-[#150707] border border-red-900/30 rounded-2xl p-5 outline-none resize-none"
        />

        <button
          onClick={handleCheck}
          disabled={loading}
          className="red-btn mt-8 flex items-center gap-3"
        >

          {loading ? (
            <>
              <Loader2
                size={22}
                className="animate-spin"
              />
              Analyzing...
            </>
          ) : (
            <>
              <Sparkles size={22} />
              Analyze Symptoms
            </>
          )}

        </button>

      </motion.div>

      {/* Loading */}

      {loading && (

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="glass-card mt-8 p-8 text-center"
        >

          <Loader2
            size={60}
            className="mx-auto animate-spin text-red-500"
          />

          <h2 className="text-3xl font-bold mt-6">
            Rapha AI is analyzing...
          </h2>

          <p className="text-gray-400 mt-4">
            Understanding symptoms...
          </p>

          <p className="text-gray-400">
            Comparing medical patterns...
          </p>

          <p className="text-gray-400">
            Preparing health insights...
          </p>

        </motion.div>

      )}

      {/* Result */}

      {response && (

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          className="glass-card mt-10 p-8"
        >

          <div className="flex items-center gap-4 mb-6">

            <div className="w-14 h-14 rounded-full bg-gradient-to-br from-red-700 to-red-500 flex items-center justify-center text-2xl">

              ❤️

            </div>

            <div>

              <h2 className="text-3xl font-bold">
                AI Health Analysis
              </h2>

              <p className="text-gray-400">
                Generated by Rapha AI
              </p>

            </div>

          </div>

          <div className="bg-[#170808] border border-red-900/30 rounded-2xl p-6 whitespace-pre-wrap leading-8 text-gray-200">

            {response}

          </div>

          <div className="mt-6 rounded-2xl border border-red-900/40 bg-red-950/30 p-5">

            <h3 className="font-bold text-red-300 mb-2">
              ⚠ Medical Disclaimer
            </h3>

            <p className="text-gray-300 leading-7">
              This AI-generated analysis is intended for informational purposes only.
              It is not a medical diagnosis or a substitute for professional medical advice.
              If your symptoms are severe, persistent, or worsening, consult a qualified healthcare provider immediately.
            </p>

          </div>

        </motion.div>

      )}

    </div>
  );
}